/* =============================================================================
   PreDeploy.sql
   =============================================================================

   Runs INSIDE the deployment transaction, BEFORE any schema change.

   Two jobs:
     1. Announce what is about to happen, so the sqlpackage log is readable.
     2. Empty the staging table.

   Emptying staging matters more than it looks. sqlpackage sometimes has to
   rebuild a table to apply a change (a column type change, adding a NOT NULL
   column). Rebuilding means copying every row into a new table inside the
   deployment transaction. On a staging table still holding three million rows
   from last night's load, that turns a five-second deployment into a
   multi-minute one that holds locks the whole time - for data that is
   worthless by definition.

   NOTE THE ASYMMETRY: this is safe for stg.* and would be catastrophic for
   fact.* or dim.*. Never extend this pattern beyond the staging schema.
   ============================================================================= */

PRINT '=========================================================================';
PRINT 'EdwTaxi.Database pre-deployment';
PRINT '  Environment : $(EnvironmentName)';
PRINT '  Database    : ' + DB_NAME();
PRINT '  Server      : ' + @@SERVERNAME;
PRINT '  Started     : ' + CONVERT(VARCHAR(30), SYSUTCDATETIME(), 126) + ' UTC';
PRINT '=========================================================================';
GO

IF OBJECT_ID('stg.YellowTaxiTrip', 'U') IS NOT NULL
BEGIN
    DECLARE @stagedRows BIGINT = (SELECT COUNT_BIG(*) FROM stg.YellowTaxiTrip);

    IF @stagedRows > 0
    BEGIN
        PRINT CONCAT('Truncating stg.YellowTaxiTrip (', @stagedRows,
                     ' rows). Staging data is regenerated by every load and is never a source of truth.');
        TRUNCATE TABLE stg.YellowTaxiTrip;
    END
END
GO

/* -----------------------------------------------------------------------------
   Refuse to deploy over a load that is currently running.

   sqlpackage may rebuild fact.YellowTaxiTrip. Doing that while
   etl.usp_Merge_YellowTaxiTrip holds a transaction on it deadlocks one of the
   two, and which one loses is not something you get to choose.

   The check is skipped in dev, where a stuck audit row is far more likely to
   be a leftover from an abandoned experiment than a real concurrent load.
   ----------------------------------------------------------------------------- */
IF '$(EnvironmentName)' <> 'dev' AND OBJECT_ID('meta.LoadAudit', 'U') IS NOT NULL
BEGIN
    DECLARE @runningLoads INT = (
        SELECT COUNT(*)
        FROM meta.LoadAudit
        WHERE Status = 'Running'
          AND StartedAtUtc > DATEADD(HOUR, -4, SYSUTCDATETIME())
    );

    IF @runningLoads > 0
    BEGIN
        RAISERROR(
            'Deployment aborted: %d load(s) are currently Running in meta.LoadAudit. Deploying now risks deadlocking against an in-flight merge. Wait for the load to finish, or mark the row Failed if you know it is stale.',
            16, 1, @runningLoads);
    END
END
GO
