/* =============================================================================
   etl.usp_Start_Load
   =============================================================================

   Opens a load audit row and returns its LoadId.

   Called by the ADF LOOKUP activity 'Start Load' in PL_Load_Sql_YellowTrip.
   A Lookup, not a Stored Procedure activity, because only Lookup can read a
   value back into the pipeline - and every subsequent step needs the LoadId.
   That is why this procedure ends in a SELECT rather than an OUTPUT parameter.

   It also enforces the duplicate-run guard. Two concurrent loads of the same
   partition would interleave in stg.YellowTaxiTrip (which is truncated per
   run) and produce a partition that is missing rows from both. Failing fast
   here is far better than discovering that later.
   ============================================================================= */

CREATE PROCEDURE [etl].[usp_Start_Load]
    @PipelineName  VARCHAR(200),
    @PipelineRunId VARCHAR(50)  = NULL,
    @TargetObject  VARCHAR(200),
    @PartitionKey  VARCHAR(50)  = NULL,
    @StaleAfterMinutes INT      = 240
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    /* ---------------------------------------------------------------------
       Reap stale rows first.

       A run that is killed mid-flight - the ADF activity times out, the
       database fails over, someone cancels the pipeline - never reaches
       usp_Complete_Load, so its audit row stays 'Running' forever and blocks
       every future load of that partition.

       Anything still 'Running' after @StaleAfterMinutes is assumed dead and
       marked Failed. Four hours is comfortably longer than the load has ever
       taken and comfortably shorter than the gap to the next scheduled run.
       --------------------------------------------------------------------- */
    UPDATE meta.LoadAudit
    SET Status         = 'Failed',
        CompletedAtUtc = SYSUTCDATETIME(),
        Message        = CONCAT(
                            'Marked Failed by etl.usp_Start_Load: still Running after ',
                            @StaleAfterMinutes,
                            ' minutes. The original run did not reach usp_Complete_Load.')
    WHERE Status = 'Running'
      AND StartedAtUtc < DATEADD(MINUTE, -@StaleAfterMinutes, SYSUTCDATETIME());

    /* ---------------------------------------------------------------------
       Concurrency guard.
       --------------------------------------------------------------------- */
    IF EXISTS (
        SELECT 1
        FROM meta.LoadAudit
        WHERE TargetObject = @TargetObject
          AND ISNULL(PartitionKey, '') = ISNULL(@PartitionKey, '')
          AND Status = 'Running'
    )
    BEGIN
        DECLARE @existingRunId VARCHAR(50) = (
            SELECT TOP (1) PipelineRunId
            FROM meta.LoadAudit
            WHERE TargetObject = @TargetObject
              AND ISNULL(PartitionKey, '') = ISNULL(@PartitionKey, '')
              AND Status = 'Running'
            ORDER BY StartedAtUtc DESC
        );

        RAISERROR(
            'A load of %s partition %s is already Running (ADF run %s). Wait for it to finish, or mark it Failed in meta.LoadAudit if you know it is dead.',
            16, 1, @TargetObject, @PartitionKey, @existingRunId);
        RETURN;
    END

    /* ---------------------------------------------------------------------
       Open the row.
       --------------------------------------------------------------------- */
    INSERT INTO meta.LoadAudit
        (PipelineName, PipelineRunId, TargetObject, PartitionKey, Status, StartedAtUtc)
    VALUES
        (@PipelineName, @PipelineRunId, @TargetObject, @PartitionKey, 'Running', SYSUTCDATETIME());

    /* SCOPE_IDENTITY, never @@IDENTITY: @@IDENTITY would return an identity
       generated by a trigger on this table if one were ever added, silently
       handing the pipeline the wrong LoadId. */
    SELECT LoadId = CONVERT(BIGINT, SCOPE_IDENTITY());
END
GO
