/* =============================================================================
   stg.YellowTaxiTrip
   =============================================================================

   Landing table for the ADF Copy activity. Column names and types mirror the
   curated Parquet EXACTLY (see curated.vw_YellowTaxiTrip in
   src/synapse/serverless/080_views_curated.sql) so that the Copy activity
   needs no explicit column mapping - ADF matches by name.

   THIS TABLE IS DESIGNED TO BE FAST TO WRITE AND NOTHING ELSE:

     * A HEAP. No clustered index, no columnstore. Both would sort or compress
       during the insert, which is pure overhead for data that will be read
       exactly once and then truncated.
     * No constraints, no defaults, no computed columns. Every one of those is
       evaluated per row on a multi-million-row bulk insert.
     * Everything NULLable, including the keys. Rejecting a bad row here would
       fail the whole copy; the merge and the data quality checks are where
       badness is dealt with, and they can report on it.

   TRUNCATED at the start of each load by the Copy activity's preCopyScript.
   Safe only because PL_Load_Sql_YellowTrip pins pipeline concurrency to 1 -
   see the comment on that activity.

   If you ever need concurrent loads, the fix is a per-run staging table name
   generated by the ETL, not a smarter truncate.
   ============================================================================= */

CREATE TABLE [stg].[YellowTaxiTrip]
(
    [TripKey]                    BINARY(16)    NULL,
    [VendorId]                   SMALLINT      NULL,
    [PickupDateTime]             DATETIME2(7)  NULL,
    [DropoffDateTime]            DATETIME2(7)  NULL,
    [PickupDate]                 DATE          NULL,
    [TripDurationSeconds]        INT           NULL,
    [PassengerCount]             SMALLINT      NULL,
    [TripDistanceMiles]          DECIMAL(9,3)  NULL,
    [PickupLocationId]           SMALLINT      NULL,
    [DropoffLocationId]          SMALLINT      NULL,
    [RateCodeId]                 SMALLINT      NULL,
    [StoreAndForwardFlag]        VARCHAR(1)    NULL,
    [PaymentTypeId]              SMALLINT      NULL,
    [FareAmount]                 DECIMAL(10,2) NULL,
    [ExtraAmount]                DECIMAL(10,2) NULL,
    [MtaTaxAmount]               DECIMAL(10,2) NULL,
    [ImprovementSurchargeAmount] DECIMAL(10,2) NULL,
    [TipAmount]                  DECIMAL(10,2) NULL,
    [TollsAmount]                DECIMAL(10,2) NULL,
    [TotalAmount]                DECIMAL(10,2) NULL,
    /* ADDED. The name must match the curated Parquet column EXACTLY: the Copy
       activity matches by name and DS_Lake_Curated_Parquet has "schema": [],
       so there is no explicit mapping to update - and no error if it is
       misspelt, just a silently NULL column. */
    [CongestionSurchargeAmount]  DECIMAL(10,2) NULL,
    [SourceFileName]             VARCHAR(400)  NULL,
    [CuratedAtUtc]               DATETIME2(7)  NULL
);
GO
